### ISSUE TITLE
Calendar: Overlapping events cause the second event to look broken across the days.

### ISSUE THREAD

**Issue by marknolaninfor** [infor-design/enterprise#1725]
**Describe the bug**
If two events span across days and there start and finish intersect then the second day will display broken across the days.

**To Reproduce**
1. Go to 'http://master-enterprise.demo.design.infor.com/components/calendar/example-index.html'
2. Click on a date and create an event from the start of the month to the selected date
3. Click on a date and create an event from the selected date to the end of the month

**Expected behavior**
That is renders similar to other month views of a calendar.

**Version**
master

**Screenshots**
![image](https://user-images.githubusercontent.com/39749678/53782186-231aa280-3f5c-11e9-8ff6-0107693d6ca0.png)

Example from outlook of an overlap in events
![image](https://user-images.githubusercontent.com/39749678/53782179-126a2c80-3f5c-11e9-92a5-2ac1d7e2ddbd.png)

**Additional context**

**Comment by tmcconechy** [comment]
We can probably change the sort to make this work better around this line:
https://github.com/infor-design/enterprise/blob/master/src/components/calendar/calendar.js#L323

Possibly sort it so the shorter duration events are first?

**Comment by marknolaninfor** [comment]
@tmcconechy Changing the sort order will just change what item appears to split. The outlook calendar looks like the second item for the day will continue on the second row for the remaining of the week and then start on the first row of the next week.

**Comment by tmcconechy** [comment]
Ok @marknolaninfor , your probably right there are cases the order might still split. We'll have to see what we can do about this one we we get a chance to get to it then.

**Comment by tmcconechy** [comment]
Simpler steps

https://master-enterprise.demo.design.infor.com/components/calendar/example-index.html
- make an all day event on June 8th
- make an all day event from June 8th - June 9th

**Comment by janahintal** [comment]
The issue still exists. Please see details below. 

Steps:
1. go to http://localhost:4000/components/calendar/test-overlaping-events.html 
2. Click the Purple 'More Meetings' date 
3. Change the date From 6/12 - 16/15 TO 6/12 - 6/17
4. Click Submit

![image](https://user-images.githubusercontent.com/45757016/84351202-706cd180-abed-11ea-9907-72dbd75b760f.png)

![image](https://user-images.githubusercontent.com/45757016/84350864-b9705600-abec-11ea-95f7-e5d7d027fb94.png)

**Comment by janahintal** [comment]
This issue is now resolved. Thank you! 
![image](https://user-images.githubusercontent.com/45757016/84987059-239b7480-b172-11ea-8b6e-624763f55899.png)

**Comment by jbrcna** [comment]
The issue still persists when you create **more than 3 events** ( `having + 1 More`). please see screenshot for reference. Thank you
`EDGE`
![image](https://user-images.githubusercontent.com/56722184/85396083-b463bd00-b583-11ea-8375-e4fd8b12bc9f.png)

`SAFARI`
![image](https://user-images.githubusercontent.com/56722184/85396261-01e02a00-b584-11ea-8155-7528cebd4358.png)

`CHROME`
![image](https://user-images.githubusercontent.com/56722184/85396396-410e7b00-b584-11ea-8209-887123ca54f7.png)

**Comment by tmcconechy** [comment]
Can you tell me the steps to reproduce this? Also lets make a new issue as i might not have time for extra cases.

**Comment by jbrcna** [comment]
Sure thing @tmcconechy . I just create multiple events with the same start date. But the 4th event's end date is just a day longer than the other 3. (e.g. create 3 events with 1-day duration [i.e. June 23 - June 23]  then create another one with 2-day duration [June 23 - June 24])
see first screenshot above for reference.

please see this separate issue for full details https://github.com/infor-design/enterprise/issues/4082

**Comment by tmcconechy** [comment]
OK lets deal with it there. its a lesser case
