### ISSUE TITLE
Hierarchy stacked tree not loading in WIn10 IE11 Browser

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#2010]
**Describe the bug**
Hierarchy stacked tree not loading in WIn10 IE11 Browser

**To Reproduce**
1. Go to http://4180-beta0-enterprise.demo.design.infor.com/components/hierarchy/example-stacked.html

**Expected behavior**
Stacked Hierarchy should display

**Version**
v4.18.0

**Screenshots**
<img width="1272" alt="Screen Shot 2019-04-25 at 3 23 11 PM" src="https://user-images.githubusercontent.com/45757016/56717106-8bbd1900-676e-11e9-962e-23e2f1c4fbb1.png">

**Platform**
Windows 10 
IE 11 

**Additional context**
No any other context about the problem here.

**Comment by tmcconechy** [comment]
This never worked since the example was created but i think this should be fixed as soon as we can.

**Comment by janahintal** [comment]
Issue still exist in http://master-enterprise.demo.design.infor.com/components/hierarchy/example-stacked.html and in localhost. Thanks!

**Comment by tmcconechy** [comment]
This will be ready on the rc build, we didn’t make that yet. But you can test on branch 4.18.x if you like

**Comment by janahintal** [comment]
QA Passed. Will move to Done. Thanks!
Verified in: http://4180-rc0-enterprise.demo.design.infor.com/components/hierarchy/example-stacked.html
