### ISSUE TITLE
Timepicker: AM/PM picker is out of position on Android devices

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#2021]
**Describe the bug**
Timepicker: AM/PM picker is out of position on Android devices

**To Reproduce**
1. Open browsers in Android
2. Go to http://4180-beta0-enterprise.demo.design.infor.com/components/timepicker/example-index.html 
and http://4180-beta0-enterprise.demo.design.infor.com/components/timepicker/example-validation.html
3. Open time picker, then open AM/PM dropdown
4. See issue: AM/PM picker is out of position

**Expected behavior**
Picker position should be correct

**Version**
- ids-enterprise: v4.17.0 - v4.18.0-beta0

**Screenshots**
<img width="429" alt="Screen Shot 2019-04-25 at 7 39 56 PM" src="https://user-images.githubusercontent.com/39508864/56733326-6510d980-6792-11e9-8e01-d88e52f0f436.png">

**Platform**
 - Android browsers

**Additional context**
No additional context.

**Comment by tmcconechy** [comment]
Verified this on a Pixel 2 Chrome, This last worked in 4.15

**Comment by davidcarlsonberg** [comment]
This seems to have been solved. Perhaps alongside the issue @tmcconechy mentions above.

**Comment by brianjuan** [comment]
Yeah it's now fixed, verified on master and 4.18.0, thanks @davidcarlsonberg for noting.

**Comment by SofiK** [comment]
Hi! I can still get this issue in https://design.infor.com/code/ids-enterprise/latest/demo/components/timepicker/example-index.html by clicking the AM/PM Field (It's opened above the first field instead of the third field)

**Comment by brianjuan** [comment]
Thanks @SofiK , yeah issue still happening. I misread the issue, I thought it's about the misaligned X icon.

**Comment by tmcconechy** [comment]
Im not seeing the issue with the dropdown issue on the actual devices. Which device in chrome is it your using? The problem is that chrome dev tools arent actual devices so its not really accurate. I think that the detection to show an X isnt working since it still thinks the browser is chrome. 

@davidcarlsonberg ?

**Comment by SofiK** [comment]
I've seen it in Android (Samsung Galaxy S7), but also in Homepages in smaller view even without using dev tools (but then the timepicker is located to the right of the screen)

**Comment by SofiK** [comment]
For example here (I've edited the example to include 3 timepickers) 
![image](https://user-images.githubusercontent.com/8664975/57534644-cb742b00-7340-11e9-9eb7-2639cbf604e7.png)

**Comment by davidcarlsonberg** [comment]
I do see the issue if you edit the example to have three time pickers in Chrome on a desktop. I do not see the issue on Android. However I do see this:
<img width="375" alt="android-timepicker" src="https://user-images.githubusercontent.com/7952168/57537289-f85e1900-7313-11e9-8f7c-11d54c5af79d.png">

**Comment by CindyMercadoReyes** [comment]
Another minor issue was found on Android mobile. When you open the dropdown list box to set the time the list box appears on the left hand corner of the UI. Please see screen shot attached. 
![bs_realdroid_Mobile_Samsung Galaxy S9-8 0-1440x2960(1)](https://user-images.githubusercontent.com/39101346/57637191-c3063500-7578-11e9-9c75-96957fafc1ba.jpg)

**Comment by CindyMercadoReyes** [comment]
Issue on Android when opening the time picker on the Calendar for RTL. Steps below:
1. Open the calendar
2. Click on the drop down list box for minutes
3. When the user clicks on the drop down list box the list box appears on the left hand corner of the UI. 
4. Please see screen shot attached.

**Comment by brianjuan** [comment]
Upon further investigation, the issue happens on Samsung Galaxy S7, S8, S9 and LG G5. 
But not on S8+,S9+ and Google Pixel devices. I also tried on actual Samsung Galaxy S8+ and the issue is not happening.

**Comment by brianjuan** [comment]
> I do see the issue if you edit the example to have three time pickers in Chrome on a desktop. I do not see the issue on Android. However I do see this:
> <img alt="android-timepicker" width="375" src="https://user-images.githubusercontent.com/7952168/57537289-f85e1900-7313-11e9-8f7c-11d54c5af79d.png">
> So, my opinion, this issue should remain reopened. A new test page with multiple time picker should be created to address the issue. And, I think, a new issue should be opened for the thing on Android mobile that I include here (black box "AM").

Hi @davidcarlsonberg , there is already an issue I created last December for the black tooltip, see #1446  . Thanks.

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
