### ISSUE TITLE
Dropdown: Destroy test case not working and causes memory leak

### ISSUE THREAD

**Issue by aaronpikkarainen** [infor-design/enterprise#2493]
**Describe the bug**
Calling the destroy api on a dropdown control doesn't release the control from memory. These memory leaks can build up over time in a SPA and cause the browser window to slow down and crash.

**To Reproduce**
1. Go to https://design.infor.com/code/ids-enterprise/latest/demo/components/dropdown/test-destroy
2. Open the Memory tab in Chrome Developer Tools
3. Click on 'Destroy Dropdown One' and 'Destroy Dropdown Two'
4. Click the 'Collect garbage' button to make sure the browser has collected garbage
5. Click the 'Take snapshot' button to see the memory heap.
6. Filter the results in the snapshot to 'dropdown' and you will see that two instances of the Dropdown control are still in memory.

**Expected behavior**
After calling the destroy api on a dropdown control it should no longer exist in memory. The destroy method needs to properly cleanup/remove things so that garbage collection will remove the control from memory.

**Version**
- ids-enterprise: v4.19.4

**Screenshots**
![image](https://user-images.githubusercontent.com/14128010/61306183-23ecfc00-a7ba-11e9-94a3-69070a482196.png)

**Platform**
 - Device: Dell Laptop
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version: 75.0.3770.142 (Official Build) (64-bit)

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.

**Comment by aaronpikkarainen** [comment]
I found that this issue is still present if you use the dropdown before destroying it. These steps will produce the issue:

1. Go to http://master-enterprise.demo.design.infor.com/components/dropdown/test-destroy.html
2. Open the Memory tab in Chrome Developer Tools
3. **Open and close each dropdown list before destroying**
4. Click on 'Destroy Dropdown One' and 'Destroy Dropdown Two'
5. Click the 'Collect garbage' button to make sure the browser has collected garbage
6. Click the 'Take snapshot' button to see the memory heap.
7. Filter the results in the snapshot to 'dropdown' and you will see that two instances of the Dropdown control are still in memory.

The cause of the problem is there is a "touchstart" event that does not get cleaned up. It is added in the "openList" function...

`$(document).on('touchstart.dropdown', touchStartCallback)`

It should be removed in the "closeList" function around line 2083.

Also, the dropdown labels are still on the screen after clicking destroy. I'm not sure what change caused that.

![image](https://user-images.githubusercontent.com/14128010/62708386-493be700-b9c1-11e9-96ab-edfa6ad55af6.png)

**Comment by brianjuan** [comment]
QA passed on https://4200-rc2-enterprise.demo.design.infor.com/components/dropdown/test-destroy.html, moving to Done,
![image](https://user-images.githubusercontent.com/39508864/62854672-90f4a280-bd22-11e9-9830-3ed828d29a6b.png)
