### ISSUE TITLE
Dropdown: Search field is not staying in its initial position

### ISSUE THREAD

**Issue by svensori** [infor-design/enterprise#2659]
**Describe the bug**
The dropdown search field is not staying in its initial position.

**To Reproduce**
1. Have a dropdown with a long list of options, which will make it show upwards. (Important to reproduce the bug.)
2. Type in the search field for a specific option only. This will make the dropdown shows downwards. This will result in the search field to be below the options instead of being above.

**Actual Results**
The search field is not consistent in its position. 

**Expected behavior**
Search field must stay in its initial position whether it has a long or short list of options.

**Version**

- ids-enterprise-ng: v5.5.1

**Screenshots**
Dropdown with long list of options:
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/33301703/63218926-41d2c580-c199-11e9-9d88-caf2c3abfacb.png)
After searching with short list of options: (See searchfield position) 
![MicrosoftTeams-image](https://user-images.githubusercontent.com/33301703/63218922-38e1f400-c199-11e9-9cee-db0b35c07b6a.png)

**Platform**
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version: Version 76.0.3809.100 (Official Build) (64-bit)

**Comment by mythilinishtala7** [comment]
Hi @tmcconechy , may I know the progress of this issue.  As I'm facing similar issue.
Thanks

**Comment by tmcconechy** [comment]
@mythilinishtala7 @svensori we had fixed some similar issues such as:

https://github.com/infor-design/enterprise/issues/3482
and
https://github.com/infor-design/enterprise/issues/3058

Could you retest this on the latest issue and let me know if this is still an issue? Try Ng 7.0.3 (using IDS 4.27.x)

Also im a little unclear on the example. Which rows where clicked / filtered on. We might need a new example to reproduce this case if its still existing?

**Comment by mythilinishtala7** [comment]
Hi @tmcconechy , the issue is something related to the position of search icon field  in the dropdown. 
Please see the attachments , in the same modal  one dropdown shows search icon field on top and the other shows in the bottom. 
![Search-IconAppearTop](https://user-images.githubusercontent.com/54135198/81261921-8e796c00-905a-11ea-95a0-79854a2b1801.PNG)
![Search-IconAppearDown](https://user-images.githubusercontent.com/54135198/81261924-8faa9900-905a-11ea-8790-1aa1d19609eb.PNG).

I'm on version 6.5.1 of ids-enterprise-ng

**Comment by tmcconechy** [comment]
Ok, and to be clear which row/cell in the screen shots are you clicking. Also i think this is fixed please try the 7.1.0 version or 6.6.0 and have a look?

**Comment by mythilinishtala7** [comment]
@tmcconechy , the issue is still there with 6.6.0 and 7.1.0 too.  And the above images I have posted are taken from a modal dialog which has series of dropdowns. The drop down which is in the top of the modal and upto a certain height, shows search icon field on top , the rest of the dropdowns in the bottom show search icon field in bottom. Just wanted to confirm with you was that intentional as I think it is adjusting itself according to modal height?  Please let me know.

**Comment by tmcconechy** [comment]
Its adjusting itself to fit where there is the most space on the size of the browser. I.E. top or bottom and depending on the number of list items.

Ideally the search box in the dropdown should be right on top of the actual input that was clicked on. But there may be some cases where thats impossible , so then we go for having it fit in the page.

This maybe improved on given the rule "he dropdown should be right on top of the actual input that was clicked on" but this will be hard to reproduce. Would you mind including the code for this modal so we can test it?

**Comment by mythilinishtala7** [comment]
Hi @tmcconechy , I have created a sample enterprise ng project and reproduced this issue. Please clone the project from https://github.com/mythilinishtala7/soho-dropdown.git .  Version here is 6.1.1. However, it is reproduced even in 6.6.0 and 7.1.1. Please let me know if any further information required.

**Comment by mythilinishtala7** [comment]
Hi @tmcconechy , is the fix available in the latest version of ids?

**Comment by tmcconechy** [comment]
This was fixed in our 4.30 codeline. Thats expected to be released in first week of July. But you can test it on master branch if you like now

**Comment by janahintal** [comment]
This issue is now resolved. Thank you! 
![image](https://user-images.githubusercontent.com/45757016/85390133-f2a8ae80-b57a-11ea-818f-e2c7259b3f65.png)
