### ISSUE TITLE
Editor: Uplift causes some editor toolbar buttons to not fully display

### ISSUE THREAD

**Issue by fitzorama** [infor-design/enterprise#2741]
**Describe the bug**
When the soho-editor is used with the uplift theme, the H3 and Visual buttons do not fully display.

**To Reproduce**
1. Go to http://localhost:4000/components/editor/example-index.html?theme=uplift&variant=light&colors=0563C2
2. The H3 button does not fully display
3. Click on the HTML button
4. The Visual button does not fully display

**Expected behavior**
The buttons should fully display

**Version**

- ids-enterprise: 4.21.0-dev

**Screenshots**
![image](https://user-images.githubusercontent.com/20212079/64364208-0547fc00-cfd8-11e9-9476-90a87542dfd7.png)
![image](https://user-images.githubusercontent.com/20212079/64364332-358f9a80-cfd8-11e9-8195-86fe0054794d.png)

**Platform**
All

**Additional context**

**Comment by tmcconechy** [comment]
This was fixed in time for 4.21-beta2 on this PR https://github.com/infor-design/enterprise/issues/2541 adding for QA to review again.

**Comment by fitzorama** [comment]
@tmcconechy After updating this morning, I am still seeing the Visual button being truncated > 4.22.0-dev.

**Comment by tmcconechy** [comment]
The fix is in the 4.21.x branch, so will be in 4.21. I'll merge this back to the dev branch now so it will work there two next nightly. (I forgot 😞 )

**Comment by fitzorama** [comment]
It looks like both the beginning and end of the Visual label is being truncated.

**Comment by fitzorama** [comment]
Ok; great.

**Comment by tmcconechy** [comment]
Merged to master so check next dev build or 4.21-beta 2 or later. Looks like this:

![Screen Shot 2019-09-06 at 1 31 05 PM](https://user-images.githubusercontent.com/814283/64448013-a606ec00-d0aa-11e9-9787-6e08aca4d6a9.png)
![Screen Shot 2019-09-06 at 1 30 57 PM](https://user-images.githubusercontent.com/814283/64448014-a606ec00-d0aa-11e9-859c-ac317dc563c6.png)

**Comment by tmcconechy** [comment]
FYI todays build ran 2 hrs ago so it will be tomorrow around noon for a new dev build

**Comment by brianjuan** [comment]
http://4210-beta2-enterprise.demo.design.infor.com/components/editor/example-index.html?theme=uplift
http://4210-beta3-enterprise.demo.design.infor.com/components/editor/example-index.html?theme=uplift
"H3" and "Visual" are now not truncated. But when you go back to Soho using ... menu, the issue still happens and you can also notice that icons are still in Uplift and not in Soho.

Steps:
1. Go to http://4210-beta2-enterprise.demo.design.infor.com/components/editor/example-index.html?theme=uplift
2. You'll notice that issue is fixed
![image](https://user-images.githubusercontent.com/39508864/64756738-7f412d80-d562-11e9-9f6a-de3634ab0a7d.png)

3. Click ... menu in the header, then select Theme, then Soho
4. See issue still happens
![image](https://user-images.githubusercontent.com/39508864/64756598-1ce82d00-d562-11e9-9894-09f144a2bd05.png)
![image](https://user-images.githubusercontent.com/39508864/64756638-3d17ec00-d562-11e9-95a3-ed120f210b15.png)

**Comment by brianjuan** [comment]
Hi, the issue that I've commented still exist in master, http://master-enterprise.demo.design.infor.com/components/editor/example-index.html?theme=uplift. Icons still don't change when you go back to Soho, and HTML/VISUAL are still cropped.

**Comment by brianjuan** [comment]
http://master-enterprise.demo.design.infor.com/components/editor/example-index.html?theme=uplift
Passed QA testing in all browsers, moving to Done.
