### ISSUE TITLE
Pop Over: Examples have issues in IE11 after changing themes.

### ISSUE THREAD

**Issue by johnbarcena** [infor-design/enterprise#2954]
**Describe the bug**
No details are displayed in pop over when you switch themes from subtle to vibrant in the popover.

**To Reproduce**
1. Go to 'http://4220-beta0-enterprise.demo.design.infor.com/components/popover/example-attached-to-textbox.html?'
2. Verify pop over
3. Switch between Themes then Verify Pop-Over
5. Same problem on the following pages:

http://4220-beta0-enterprise.demo.design.infor.com/components/popover/example-alternate-positions.html
http://4220-beta0-enterprise.demo.design.infor.com/components/popover/example-header-color.html 
http://4220-beta0-enterprise.demo.design.infor.com/components/popover/example-extra-css-class.html

**Expected behavior**
Should display details after changing themes.
Can be corrected by refreshing the page after

**Version**
4.22 Beta - And all previous versions

**Screenshots**
![image](https://user-images.githubusercontent.com/52902639/66564010-9db23d00-eb91-11e9-8e99-72f237433b76.png)

**Platform**
IE 11

**Comment by tmcconechy** [comment]
I combined #2955 into one issue. However, i'm not seeing any big layout issues when changing themes here. I do see some minor styling adjustments that could be made for example to the title.

**Comment by tmcconechy** [comment]
Rather than having tons of different issues for the same problem i combined this all in one as this is going to be one fix. If we do fix as its a minor demo app issue

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.

**Comment by jbrcna** [comment]
Test **Failed**

The issue still persist in `extra css class`. Other example pages were fine

Verified in http://4240-beta0-enterprise.demo.design.infor.com/components/popover/example-extra-css-class.html


_See the color of popover_
<img width="1166" alt="image" src="https://user-images.githubusercontent.com/56722184/70898744-3f418900-2030-11ea-9f39-a510efb3665d.png">

**Comment by tmcconechy** [comment]
I fixed an additional issue with this in 4.25 here https://github.com/infor-design/enterprise/pull/3247
We dont think this is worth spending any more time on as this is extremely minor and a demo app issue.

Moving to done for now
