### ISSUE TITLE
Calendar: In week view, clicking "Today" changes the start of the week to day today

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#3096]
**Describe the bug**
Calendar: In week view, clicking "Today" changes the start of the week to day today.

**To Reproduce**
1. Go to http://4230-beta0-enterprise.demo.design.infor.com/components/calendar/example-index.html
2. Select "Week" on the dropdown at the top-right of the Calendar
3. The Calendar will update to week view
4. Click "Today" in the Calendar or inside the date picker
5. See issue: The week view will now start at the day today instead of Sunday

**Expected behavior**
In week view, week should always start at Sunday regardless of day today.

**Version**
- ids-enterprise: v4.23.0-beta0

**Screenshots**
![image](https://user-images.githubusercontent.com/39508864/68670957-281eff80-0589-11ea-9d62-9f06af9a1936.png)

**Platform**
 - All OS and devices.

**Additional context**
N/A.

**Comment by brianjuan** [comment]
Also happens in http://4230-beta0-enterprise.demo.design.infor.com/components/week-view/example-two-weeks.html#

**Comment by tmcconechy** [comment]
The pending fix should fix that case as well

**Comment by jbrcna** [comment]
**QA FAILED**
The issue persists.

Verified in 
http://4230-rc0-enterprise.demo.design.infor.com/components/calendar/example-index.html?

http://4230-rc0-enterprise.demo.design.infor.com/components/week-view/example-two-weeks.html?#

**Steps to replicate**

1. Go to http://4230-beta0-enterprise.demo.design.infor.com/components/calendar/example-index.html
2. Select "Day" on the dropdown at the top-right of the Calendar
3. The Calendar will update to Day view
4. Go to Future Date. Alternatively, just click the "**>**" button twice
5. Switch to "Week" view
6. The Calendar will update to Week view
7. Click "Today" in the Calendar or inside the date picker
8. _See issue:_ The week view will start at the day today instead of Sunday

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
