### ISSUE TITLE
Popover: Extra Css label is not readable

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#3242]
**Describe the bug**
the label in `popover` is hard to read

**To Reproduce**
1. Go to https://master-enterprise.demo.design.infor.com/components/popover/example-extra-css-class.html?theme=uplift&variant=dark
2. Click popover
3. See error

**Expected behavior**
Popover's label should be readable

**Version**
4.23

**Screenshots**

![image](https://user-images.githubusercontent.com/56722184/70797140-dadbbb00-1dde-11ea-9884-7a127b8685aa.png)

**Platform**
All

**Additional context**

**Comment by jbrcna** [comment]
QA **Failed**
Verified in https://master-enterprise.demo.design.infor.com/components/popover/example-extra-css-class.html?theme=soho&variant=dark

**Notes:**
It works fine in ALL Browsers **Except**  in IE11
![image](https://user-images.githubusercontent.com/56722184/71513286-a2ef7000-28d4-11ea-8ba1-20f7a74e52b3.png)

_Will retest in IE once 4.25.0-beta is deployed._

**Comment by tmcconechy** [comment]
Fixed on https://github.com/infor-design/enterprise/issues/3289 - ready to retest IE 11

**Comment by CindyMercadoReyes** [comment]
Retested this issue on Win 10 IE 11 and it's now working as expected.

**Comment by jbrcna** [comment]
The issue persist in IE 11 when you switch `themes` or `variant` or `color`. you need to refresh the page so that the issue will not occur. see sceenshot
<img width="1199" alt="image" src="https://user-images.githubusercontent.com/56722184/71708412-2c022c00-2e2c-11ea-80ea-f282aca40cad.png">
will move to Fail Column

**Comment by CindyMercadoReyes** [comment]
Retested this issue on Win 10 IE 11. This issue is now resolved. Moving this ticket to the Done column.
