### ISSUE TITLE
Soho Mask: No digits allowed in the field if the first digit is a zero

### ISSUE THREAD

**Issue by Sovia** [infor-design/enterprise#3315]
**Describe the bug**
A <input type="number"> or <input type="text"> field with a soho-mask on it doesn't allow any digits to be entered if the first digit entered is a 0.

**To Reproduce**
1. Go to /components/mask/test-input-type-numeric.html
2. Enter '0' in the Numeric Input field. This will cause an error in the console
3. Attempt to continue entering digits in the field
4. See error, no other digits are allowed

**Expected behavior**
The user is still allowed to enter digits after the 0, and when the field is blurred the mask should remove the leading zero (or whatever correct behavior the allowLeadingZeroes option is)

**Version**

- ids-enterprise: v4.25.0-dev

**Screenshots**
![SohoMaskIssue](https://user-images.githubusercontent.com/22107636/72180168-36807080-33ac-11ea-958d-fb6e3f45d0b2.gif)

Error seen in the console after entering a 0 into a <input type="number"> with a soho-mask on it:
![image](https://user-images.githubusercontent.com/22107636/72180259-63348800-33ac-11ea-9415-f1dcaa5b9713.png)

**Platform**
 - All

**Comment by janahintal** [comment]
Hello @tmcconechy, there is no console error found. However, I can still add a character after filling in the mask. Please see below. 

![image](https://user-images.githubusercontent.com/45757016/72511975-79e44e80-3886-11ea-8a49-4a16fe68d273.png)

**Comment by tmcconechy** [comment]
It is valid to enter a character here. The bug was that you could not enter anything and now you can without an error. So moving back to done, nothing to change here

**Comment by EdwardCoyle** [comment]
@tmcconechy I'm actually working on a fix for this because it's still possible to enter a second decimal into the field when it's configured as a number mask.  Trying to figure that out for a second Q/A round.

What we've discovered with this issue in general is that this should be considered an edge case, and it's not a great idea to mask a number-only input, since it's idea of what's "valid" might conflict with the mask's idea of what's valid.

**Comment by janahintal** [comment]
This issue is now resolved in http://4250-rc0-enterprise.demo.design.infor.com/components/mask/test-input-type-numeric?theme=uplift&variant=light. Thank you. Will now move to Done.

**Comment by Sovia** [comment]
I'm still seeing an issue on some fields. For example, on /components/mask/test-negative-numeric-mask.html

If you enter a 0 as the first digit in the first input, you are not able to enter any more digits afterwards. If the first digit is something other than 0, then you can enter up to the mask of values.

![ZeroFirstDigitNotWorking](https://user-images.githubusercontent.com/22107636/73304766-7afa7180-41de-11ea-8401-c46f61387cd7.gif)

**Comment by EdwardCoyle** [comment]
@Sovia @tmcconechy the configuration on that example wasn't set up to allow leading zeroes.  However, I made a quick sample page up that includes the leading zeroes setting on similar samples and can confirm this is an issue on standard text fields.  The fix we made for allowing the leading zero on a number input still works.

**Comment by Sovia** [comment]
So there is a setting for it? Sorry, I missed that.

**Comment by EdwardCoyle** [comment]
Yeah, you can set it directly on the API:
```js
$('#my-masked-field').mask({
  process: 'number',
  patternOptions: {
    allowLeadingZeroes: true
  }
});
```
...or as a `data-options` entry:
```html
<input type="number" id="test1" data-mask data-options="{ pattern: '-###,###.00', mode: 'number', negative: true, patternOptions: { allowLeadingZeroes: true }}" />
```

The case I need to fix is specifically using that setting on a Mask against a standard, text-based input field.

**Comment by tmcconechy** [comment]
This should be closed now
