### ISSUE TITLE
Datagrid: Some columns have no border in Uplift/Dark

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#3684]
**Describe the bug**
when using Uplift/Dark some columns have no border

**To Reproduce**
1. Go to https://4270-beta0-enterprise.demo.design.infor.com/components/datagrid/example-grouping-editable.html?theme=uplift&variant=dark
2. Ensure that you are using `Vibrant` Theme and `Dark` Variant
3. See error

**Expected behavior**
Datagrid should have border in all lines

**Version**
v4.27.0-beta0

**Screenshots**
![image](https://user-images.githubusercontent.com/56722184/78022817-2fa04300-7388-11ea-8299-5ccd9657c130.png)

**Platform**
All

**Additional context**

**Comment by tmcconechy** [comment]
Duplicate of #3677

**Comment by tmcconechy** [comment]
Should be fixed on RC

**Comment by jbrcna** [comment]
**QA Failed**
The issue still persists.
v4.27.0-rc0
https://4270-rc0-enterprise.demo.design.infor.com/components/datagrid/example-grouping-editable.html?theme=uplift&variant=dark
![image](https://user-images.githubusercontent.com/56722184/78339315-da05a980-75c6-11ea-839d-40a95ebb8d7c.png)

**Comment by tmcconechy** [comment]
This was actually a duplicate of https://github.com/infor-design/enterprise/issues/3649 
I fixed in 4.28 not 4.27 so you cant see it yet. Moving this

**Comment by tmcconechy** [comment]
See https://master-enterprise.demo.design.infor.com/components/datagrid/example-grouping-editable.html?theme=uplift&variant=dark

**Comment by jbrcna** [comment]
Thank you for clarifying @tmcconechy . will retest this once beta for 4.28 is released.
this is what I see on master
<img width="1405" alt="image" src="https://user-images.githubusercontent.com/56722184/78536678-cc4b6080-7820-11ea-8ac0-8837741c89c0.png">

**Comment by jbrcna** [comment]
The issue still persists.
v4.28.0-dev
verified in https://master-enterprise.demo.design.infor.com/components/datagrid/example-grouping-editable.html?theme=uplift&variant=dark

**Comment by jbrcna** [comment]
This is now working as expected. Test is done across all browsers
v4.28.0-dev
verified in https://master-enterprise.demo.design.infor.com/components/datagrid/example-grouping-editable.html?theme=uplift&variant=dark
![image](https://user-images.githubusercontent.com/56722184/79757648-f63b7180-834e-11ea-8d0e-b37edddd26dd.png)
