### ISSUE TITLE
Datagrid: Frozen column sort breaks layout

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#3735]
**Describe the bug**
Happened on this bug and its probably important. Will not patch for now since im the only one that saw it so far.

**To Reproduce**
1. Go to https://master-enterprise.demo.design.infor.com/components/datagrid/example-frozen-columns.html or https://latest-enterprise.demo.design.infor.com/components/datagrid/example-frozen-columns.html
2. Click on and sorted column in the middle
3. See error

**Expected behavior**
Its adding an extra gap for the frozen section. Should be an easy fix. May require a patch.

**Version**
- ids-enterprise: [e.g. v4.27.x]

**Screenshots**
![Screen Shot 2020-04-10 at 4 56 38 PM](https://user-images.githubusercontent.com/814283/79022580-498e1280-7b4c-11ea-92ce-d69c9ebf8d07.png)

**Platform**
 - Chrome

**Comment by tmcconechy** [comment]
Fixed in https://github.com/infor-design/enterprise/commit/92350d7192710ddd9fd2117b975e1389be2eb98c

**Comment by janahintal** [comment]
Issue still exist. Verified in 
https://master-enterprise.demo.design.infor.com/components/datagrid/example-frozen-columns.html
![image](https://user-images.githubusercontent.com/45757016/79218931-e1109f80-7e83-11ea-969e-70a90864e43f.png)
https://latest-enterprise.demo.design.infor.com/components/datagrid/example-frozen-columns.html
![image](https://user-images.githubusercontent.com/45757016/79218949-e79f1700-7e83-11ea-8721-f2f037f82723.png)

**Comment by tmcconechy** [comment]
This was not correctly deployed. The fix is deployed on https://master-enterprise.demo.design.infor.com/components/datagrid/example-frozen-columns.html

**Comment by janahintal** [comment]
The issue is now resolved in master. 
https://master-enterprise.demo.design.infor.com/components/datagrid/example-frozen-columns.html?theme=uplift&variant=light thank you!
