### ISSUE TITLE
TimePicker control having issue with African language (af-ZA)

### ISSUE THREAD

**Issue by prasannapatil91infor** [infor-design/enterprise#3750]
**Describe the bug**
TimePicker Control changes the value of AM/PM in African language (af-ZA)

**To Reproduce**
1. Go to http://localhost:4000/components/datepicker/test-12hr-time.html?locale=af-ZA
1. Click on TimePicker control and select a date with vm. as the am/pm value
1. Tab out 
1. See that the am/pm value changes

**Expected behavior**
After localization the TimePicker Control should retain the selected AM/PM format

**Version**
- v4.20.0 to 4.27

**Screenshots**
![ScreenShot4](https://user-images.githubusercontent.com/63697721/79302643-971ecc80-7f0a-11ea-8ace-c1b732d8aca1.PNG)

**Platform**
-OS Version: Windows 10
-Browser Name: Chrome
-Browser Version: 80.0.3987.163 (Official Build) (64-bit)

**Comment by tmcconechy** [comment]
This happens in any locale with a . at the end of the dayPeriod. Like el-GR, fi-FI ect.
So should be fixed and not be removing the dots.

**Comment by tmcconechy** [comment]
Related issue https://github.com/infor-design/enterprise/pull/3561/files should have been fixed here...

**Comment by janahintal** [comment]
Issue still exist in 
https://master-enterprise.demo.design.infor.com/components/datepicker/test-12hr-time.html?locale=af-ZA
https://master-enterprise.demo.design.infor.com/components/datepicker/test-12hr-time.html?locale=fi-FI

Steps:
1. Change to time to nm/ip.
2. Open the Timepicker again
3. Notice that the am/pm doesn't maintain its value. 

![image](https://user-images.githubusercontent.com/45757016/79858658-563f2000-8402-11ea-92a8-5638e1b2b817.png)

![image](https://user-images.githubusercontent.com/45757016/79858734-753db200-8402-11ea-91ac-3b26b98a1a17.png)

**Comment by janahintal** [comment]
This issue is now resolved. Thank you. :)
Verified in https://master-enterprise.demo.design.infor.com/components/datepicker/test-12hr-time.html?theme=uplift&variant=light&locale=af-ZA.
