### ISSUE TITLE
Spinbox - Using a range of 100 to 200 does not allow manual editing

### ISSUE THREAD

**Issue by dhumalkishor** [infor-design/enterprise#3909]
**Describe the bug**
We have used spinbox control in editable datagrid and when user try to put some values manually in the spinbox it is get updated.  Please refer attached image for more details. 

**To Reproduce**
1. Edit app/views/components/spinbox/example-index.html
2. Change settings to `data-options="{min: 100, max: 200}"`
3. Open the spin box page in the browser
4. try to type 111 in the field
	
**Expected behavior**
User should be able to modify spinbox values manually. (Without using "+" and "-" buttons) 

**Version**
- ids-enterprise: [4.20.0]

**Screenshots**

**Platform**
 - Chrome

**Additional context**
Ms teams

**Comment by dhumalkishor** [comment]
![_thumb_1498344](https://user-images.githubusercontent.com/42198413/81693111-10afc900-947d-11ea-9fac-b7c4713cc8d3.png)

**Comment by dhumalkishor** [comment]
Hi Tim,

Can we get this issue fixed in Enterprise 4.29.x version? We have planned to upgrade this version once it available.

**Comment by tmcconechy** [comment]
We can try but i cannot guarantee as that sprint is ending and we still have a lot to do. I will put it in for now but we may have to push it.

**Comment by dhumalkishor** [comment]
Thanks Tim.

**Comment by tmcconechy** [comment]
A workaround for this issue is to set 
```
this.settings.autocorrectOnBlur: true
```
This will not mangle up the keying but will only validate to a min or max value on tab out.

**Comment by CindyMercadoReyes** [comment]
Hello, This issue failed in Win 10 IE 11. I was able to enter "1996" in the field box. Please see screen shot attached. 
![bs_win10_IE_11 0 (1)](https://user-images.githubusercontent.com/39101346/82257618-5c072300-9926-11ea-9a1b-97abe713754d.jpg)

**Comment by tmcconechy** [comment]
@CindyMercadoReyes if you tab out it will reset the value to max. it does not do it while in the field but it should only let you type 3 digits not 4 before it corrects on tab.

This is a seperate bug so i filed https://github.com/infor-design/enterprise/issues/3939
