### ISSUE TITLE
Locale: Literal and grammatically incorrect "Row Height" translations. Translations need to be reviewed / tested at run-time by linguists

### ISSUE THREAD

**Issue by cpinatel7** [infor-design/enterprise#4336]
Literal and grammatically incorrect "Row Height" translations. Translations need to be reviewed / tested at run-time by linguists

Court
Moyen
Normal
are grammatically incorrect in French (France).

Court is very literal

Screenshot attached
![RowHeight](https://user-images.githubusercontent.com/66057969/91992568-94dfd200-ed34-11ea-919d-ac0aaea3e2f0.png)

**Comment by cpinatel7** [comment]
Can you please assign it to Henry Wondergem? Thanks

**Comment by tmcconechy** [comment]
Sure feel free. I updated the translations to the latest on //nlbavwmemoq2.infor.com/cc/FromDev/SohoUX/en-US.js for the translation team. Not sure how they take note of this?

Also i made an in-context translation page. 
https://master-enterprise.demo.design.infor.com/components/locale/test-translations.html&locale=es-ES for testing a bit better append the locale at the end you want to test (some new strings missing still).

**Comment by tmcconechy** [comment]
cc @hwondergem

**Comment by janahintal** [comment]
This issue is now resolved. 
Tested in
![image](https://user-images.githubusercontent.com/45757016/97152878-8bab3880-17ac-11eb-836d-54cc4868be03.png)

**Comment by cpinatel7** [comment]
Not fixed

**Comment by cpinatel7** [comment]
Not fixed. The Gender for Hauteur is Feminine. Adjectives are in the Masculine form

**Comment by janahintal** [comment]
Thanks, @cpinatel7 for confirming. 

Here's what is stated in the PR for testing: 
go to http://localhost:4000/components/datagrid/example-index.html?locale=fr-FR -> should not say "court" for short in the row heights in the ... menu

Can you give me the exact **Expected** fix for this issue?

**Comment by cpinatel7** [comment]
Très petite
Petite
Moyenne
Grande

**Comment by janahintal** [comment]
Thank you, will move to Failed QA. 

**Actual:**  https://master-enterprise.demo.design.infor.com/components/datagrid/example-index.html?locale=fr-FR
![image](https://user-images.githubusercontent.com/45757016/97155166-e6925f00-17af-11eb-85e2-b91e6973ef9c.png)


**Expected:** 
Très petite
Petite
Moyenne
Grande

**Comment by tmcconechy** [comment]
cc @hwondergem - could we please get this corrected in the translation files?

**Comment by tmcconechy** [comment]
FYI - Added a comment in the strings to help for next time translating

**Comment by tmcconechy** [comment]
This is now:
![Screen Shot 2020-12-11 at 10 45 06 AM](https://user-images.githubusercontent.com/814283/101923926-033af880-3b9e-11eb-9c4b-7b612a5d5049.png)

**Comment by hwondergem** [comment]
Hi tmmconechy, the French translations should be OK; not sure why you don't see the correct forms. File: 
\\nlbavwmemoq2\cc\ToDev\SohoUX\fr-FR.js	46,183	12/11/2020 07:54	-a--
![image](https://user-images.githubusercontent.com/67783011/102094470-a603a900-3e22-11eb-9409-3c0229211657.png)

**Comment by tmcconechy** [comment]
<img width="245" alt="Screen Shot 2020-12-14 at 9 54 22 AM" src="https://user-images.githubusercontent.com/814283/102096142-5f965600-3df2-11eb-9427-f0b5e51a6fc8.png">

Sorry this is what it is now. So i think its all corrected...

**Comment by janahintal** [comment]
This issue is now resolved. 

**Expected:**
Très petite
Petite
Moyenne
Grande

Actual: https://master-enterprise.demo.design.infor.com/components/datagrid/example-index.html?theme=uplift&variant=light&colors=0066D4&locale=fr-FR
![image](https://user-images.githubusercontent.com/45757016/102202678-9c517280-3f02-11eb-8ee9-cba9ef5dfff4.png)
