### ISSUE TITLE
Datagrid: Icons looks misaligned when focused

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#4480]
**Describe the bug**
Datagrid: Icons looks misaligned when focused

**To Reproduce**
1. Go to https://master-enterprise.demo.design.infor.com/components/datagrid/example-grouping.html
2. Change the row height to Extra Small
3. Click '-' button in Hardware Customer row
4. Play with the button 'til its focused

**Expected behavior**
Icons should be aligned

**Version**
4.34 ids dev

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/95841397-e89ffb00-0d77-11eb-8f71-1c44c8f2ce31.png)

**Platform**
All major browsers

**Additional context**
N/a

**Comment by tmcconechy** [comment]
Fixed this on a non related PR. Please retest for 4.35

**Comment by janahintal** [comment]
The issue still exists in https://master-enterprise.demo.design.infor.com/components/datagrid/example-grouping.html

![image](https://user-images.githubusercontent.com/45757016/97690720-5407fd80-1ad8-11eb-9d73-eab0be2f2ec8.png)

**Comment by tmcconechy** [comment]
My mistake i actually fixed something else.

**Comment by janahintal** [comment]
Hi @tmcconechy , the issue still exists in https://master-enterprise.demo.design.infor.com/components/datagrid/example-grouping.html

Steps: 
1. go to https://master-enterprise.demo.design.infor.com/components/datagrid/example-grouping.html?theme=soho&variant=light&colors=2578a9
2. Click - in Hardware Customer Row
3. Open other tab or go to other tab
4. Go back and check the icon. Notice that the focus is not aligned 

![image](https://user-images.githubusercontent.com/45757016/98784595-52bec500-2436-11eb-8a6e-6b8a22506cde.png)

![image](https://user-images.githubusercontent.com/45757016/98784562-46d30300-2436-11eb-879d-dde91114750f.png)

**Comment by tmcconechy** [comment]
@ericangeles can you take another look?

**Comment by ericangeles** [comment]
@tmcconechy sure.

**Comment by janahintal** [comment]
This issue is now resolved in https://master-enterprise.demo.design.infor.com/components/datagrid/example-grouping.html?theme=uplift&variant=light&colors=0066D4

![image](https://user-images.githubusercontent.com/45757016/99353425-6effad80-28df-11eb-82a3-a3542b0fddcf.png)
