### ISSUE TITLE
TimePicker: Issue with AM/PM in Chinese language (zh-CN)

### ISSUE THREAD

**Issue by dhumalkishor** [infor-design/enterprise#5420]
**Describe the bug**
Time picker control is not working properly with Chinese language.

**To Reproduce**
1. Set Soho Locale to zh-CN.
2. Open timepicker and select hour and minute value.
3. Click on 'Set Time' button (It would be translated in Chinese)
4. It will show error '无效时间' (Invalid time I guess).

Also, after re-opening the timepicker the Minute value will be get transferred to Hour value and Minute value becomes zero.

Or we can reproduce the same issue with below link.

https://main-enterprise.demo.design.infor.com/components/timepicker/example-index.html?locale=zh-CN
Steps to follow to reproduce the issue.

1. Open timepicker and select hour and minute value.
2. Click on 'Set Time' button (It would be translated in Chinese)
3. It will show error '无效时间' (Invalid time I guess).

**Expected behavior**
Time picker should show correct values on revisit. 

**Version**
- ids-enterprise-ng: V4.53.0

**Screenshots**
![MicrosoftTeams-image (7)](https://user-images.githubusercontent.com/42198413/125456319-cab98874-efe7-4af5-8f85-23132392e27c.png)

**Platform**
 - Device (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name [e.g. chrome, safari, stock browser]
 - Browser Version [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**

**Comment by cpinatel7** [comment]
When can we expect a resolution for this issue? It's a showstopper for this new GRC language. Thanks

**Comment by tmcconechy** [comment]
This is schedule for next months release (July - Aug)

**Comment by cpinatel7** [comment]
Will your fix be limited to the "time" area? I need to assess what can be tested or not in Chinese S. as we'll have to go ahead with our first round of testing without your fix. Thanks

**Comment by tmcconechy** [comment]
Yeah the fix would be limited to what is written above. Although we probably should test other locales with translated AM/PM. I expect this would impact just the timepicker but possibly need a change to the locale time/converstion

**Comment by cpinatel7** [comment]
Thanks Tim

**Comment by tmcconechy** [comment]
cc @deep7102 as he has fixed similar issues before just get in touch with him if you need @ericangeles

**Comment by nganotice** [comment]
Hi @tmcconechy - it's already working as it is but I've noticed a minor issue with the consistency of the movement when the time is picked from:

https://main-enterprise.demo.design.infor.com/components/timepicker/example-index.html?locale=zh-CN
https://main-enterprise.demo.design.infor.com/components/timepicker/example-index.html?locale=zh-Hans
https://main-enterprise.demo.design.infor.com/components/timepicker/example-index.html?locale=zh-Hant
![CN](https://user-images.githubusercontent.com/84306838/130210011-f62d669b-1a6a-4d08-8796-e9314178b23e.gif)

While with https://main-enterprise.demo.design.infor.com/components/timepicker/example-index.html?locale=zh-TW - there's no movement at all (the same with https://main-enterprise.demo.design.infor.com/components/timepicker/example-index.html)
![Copy of TW ](https://user-images.githubusercontent.com/84306838/130209978-297e4a65-0e8e-4441-9271-544cc18a9915.gif)

Just want to confirm if this will be an issue? Thanks!

**Comment by tmcconechy** [comment]
It shouldnt be a big deal but i think im going to fail it and ask @ericangeles to improve it as the text is off center and it seems like it might be related to the fix

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.

**Comment by dhumalkishor** [comment]
We have reviewed 4.55.3 SoHo library version and found that this issue is not fixed for zh-CN language. Please refer attached video for more details. 

https://user-images.githubusercontent.com/42198413/136017908-f1386790-64a3-4b41-9469-46f5cdc7f9c4.mp4

**Comment by tmcconechy** [comment]
The issue appears fixed on our end if you test out https://4551-enterprise.demo.design.infor.com/components/timepicker/example-index.html?locale=zh-CN or https://main-enterprise.demo.design.infor.com/components/timepicker/example-index.html?locale=zh-CN

So I'm not able to reproduce the issue any further. I'm assuming  perhaps you didn't get the fix properly? Its hard to make out what your typing in the video. Maybe try installing ids-enterprise-ng 10.6.3 as you could be getting the old version thats installed with ids-enterprise-ng

**Comment by ericangeles** [comment]
@tmcconechy will take a look

**Comment by tmcconechy** [comment]
Right makes sense. Good catch @ericangeles the timeFormat is hardcoded to the wrong one that doesn't match Chinese. https://github.com/infor-design/enterprise-ng/blob/main/src/app/timepicker/timepicker.demo.html#L21

I think it will also work if you remove the time format entirely then it will use the current locale by default
