### ISSUE TITLE
Non-clearable searchfield not rendering properly on Mac OS Safari

### ISSUE THREAD

**Issue by kwolentarski** [infor-design/enterprise#6842]
**Describe the bug**
When using searchfield component with clearable set to false there is a console error while rendering the component on Mac OS Safari:
![image](https://user-images.githubusercontent.com/86295640/191553543-dc525414-ef08-4969-bf6e-3a9cba3c1d8c.png).

Issue probably introduced as part of: https://github.com/infor-design/enterprise/issues/6631

**To Reproduce**

1. Use Safari browser or use Chrome Device Mode and set some Mac device
2. Go to https://main-enterprise.demo.design.infor.com/components/toolbar-flex/test-header-like-title-in-span.html
3. Notice the error in console

**Expected behavior**
Searchfield without clearable option should render properly

**Version**

- ids-enterprise: latest

**Platform**
 - Infor Application/Team Name: Infor WFM
 - Browser Name: Safari, Chrome Device Mode

**Comment by tjamesallen15** [comment]
Hello. Verified on 4.69.0 and it's not reproducible anymore. This was fixed by another PR. https://github.com/infor-design/enterprise/issues/6858

**Comment by janahintal** [comment]
The issue still exists in MacOS Safari 14.1 Big Sur. 

**Chrome**
![image](https://user-images.githubusercontent.com/45757016/197522347-b5b88c76-5c2e-461d-add3-e61f477fafec.png)

**Safari 14.1 Big Sur**
![image](https://user-images.githubusercontent.com/45757016/197534960-11a9b200-3cce-42db-97cf-dc8b37c11ea4.png)

**Comment by tmcconechy** [comment]
@tjamesallen15 i think its possible this wasnt deployed as we had issues there.?

**Comment by jbrcna** [comment]
this is failing in main but works fine in localhost. 
will retest once fix is available in main
https://main-enterprise.demo.design.infor.com/components/toolbar-flex/test-header-like-title-in-span.html
<img width="546" alt="image" src="https://user-images.githubusercontent.com/56722184/197155535-e3da2588-193c-46ad-85a9-1c6f9f5b17b2.png">

http://localhost:4000/components/toolbar-flex/test-header-like-title-in-span.html
<img width="1208" alt="image" src="https://user-images.githubusercontent.com/56722184/197155660-0fbb69d0-f3ab-4f8f-bff0-1b5b2973e5ee.png">

**Comment by janahintal** [comment]
QA Passed. Verified in https://main-enterprise.demo.design.infor.com/components/toolbar-flex/test-header-like-title-in-span.html. Thanks!
![image](https://user-images.githubusercontent.com/45757016/199519584-e1b7e184-2367-4fa7-a4a1-a593115eb5c4.png)
![image](https://user-images.githubusercontent.com/45757016/199519663-e53709cc-5d91-4bf7-98af-9bf4b68760e5.png)
