### ISSUE TITLE
Datepicker: month picker highlight issue

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#6865]
**Describe the bug**

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/datepicker/example-timeformat.html
2. Click on calendar icon of `Date Time Timestamp` field
3. Open month picker

**Expected behavior**
blue highlight should not exceed the separator

**Version**

- ids-enterprise: v4.68.0-dev

**Screenshots**
<img width="322" alt="image" src="https://user-images.githubusercontent.com/56722184/193016309-ff27a6e5-d21b-4ce3-af06-bbd486de1de9.png">

**Platform**
all

**Additional context**

**Comment by tmcconechy** [comment]
@jbrcna are you zoomed? Im not seeing it look exactly like that

**Comment by jbrcna** [comment]
no it is not zoom in/out. here's a screenshot in Browserstack 
<img width="1671" alt="image" src="https://user-images.githubusercontent.com/56722184/193167964-5cc93f27-4124-4bce-a283-2db940a3b696.png">

**Comment by tmcconechy** [comment]
Ok i see it if you make less space on the bottom and it moves to the side instead

**Comment by jbrcna** [comment]
this issue is now resolved.
<img width="455" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/8df859b8-6376-47b4-8799-6645b0a1b488">

**Comment by RJ-Csc** [comment]
Upon checking, this issue seems to have been resolved already. 
<img width="860" alt="image" src="https://github.com/infor-design/enterprise/assets/75935158/fa8ef52d-b269-4edb-b3df-1451782f71c5">

**Comment by jbrcna** [comment]
this has been working previously. however, when testing is again on main (v4.88.0-beta.0) the issue persist in safari browser
<img width="655" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/4d26fcd4-7aaa-4dc2-86ac-32fb3e17a4e0">

**Comment by RJ-Csc** [comment]
Addressed in https://github.com/infor-design/enterprise/pull/8011

**Comment by jbrcna** [comment]
this is now working as expected
<img width="891" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/348d2d84-c779-4480-b1aa-225968525420">
