### ISSUE TITLE
DatePicker: Icon not getting stuck to the date input and floating

### ISSUE THREAD

**Issue by sanketughade** [infor-design/enterprise#7144]
When a form is placed on the dialog(which opens on a button click) and if the last form field is date picker input field(soho-datepicker) the date-picker icon floats somewhere else and doesn't stick to the date-picker input control as shown in the screenshot below,

<img width="960" alt="date" src="https://user-images.githubusercontent.com/30241282/215403512-4ba73765-a591-4b88-98fa-c38641d92c86.png">

I have reproduced this issue on stackblitz for **ids-enterprise version - 4.70.0** and **ids-enterprise-ng version - 14.7.1**, below is the link of stackblitz,
https://stackblitz.com/edit/ids-quick-start-1450-rd9ird?file=package.json

**NOTE**: If there is only date-picker form field on the form then the date-picker icon doesn't float somewhere else and works completely fine.

**Comment by tmcconechy** [comment]
In the future please follow the issue template https://github.com/infor-design/enterprise/issues/new/choose (dont just delete it). But this issue is pretty clear. Just for future, we like to see the template being used.

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.

**Comment by sanketughade** [comment]
I can still reproduce this issue for **ids-enterprise - 4.82.0** and **ids-enterprise-ng - 15.2.1** on stackblitz. Below is the link to stackblitz application:

 

[https://stackblitz.com/edit/ids-quick-start-1521-14jgd7?file=package.json](url)

**Comment by tmcconechy** [comment]
@sanketughade can you fix the link it goes to github?

**Comment by sanketughade** [comment]
@tmcconechy I don't know why this is happening but can you please try copying and pasting it in your browser??

**Comment by sanketughade** [comment]
@tmcconechy I don't know why this is happening but can you please try copying and pasting it in your browser??

**Comment by sanketughade** [comment]
@tmcconechy I can clearly see the issue. Try zooming your browser's screen or try on some small screen device.
<img width="960" alt="Screenshot 2023-04-13 195452" src="https://user-images.githubusercontent.com/30241282/231790125-f272e6eb-e9bd-4fe2-a1fc-9ed60fe2d944.png">

**Comment by sanketughade** [comment]
@tmcconechy I can clearly see the issue. Try zooming your browser's screen or try on some small screen device.
<img width="960" alt="Screenshot 2023-04-13 195452" src="https://user-images.githubusercontent.com/30241282/231790301-b92a491f-07cf-483c-959f-d0791d96a30d.png">

**Comment by tmcconechy** [comment]
ok yeah sorry we were not testing it this way. I reopened. Tried to make the steps a bit clearer for @tjamesallen15 https://github.com/infor-design/enterprise/issues/7144#issuecomment-1507076233

**Comment by tmcconechy** [comment]
thanks @tjamesallen15 makes sense. @sanketughade just update your mark up as noted please and it should fix it.
