### ISSUE TITLE
Paging: After re-assigning gridOptions the SohoDataGridSourceRequest object the object is missing the type variable

### ISSUE THREAD

**Issue by pallisj** [infor-design/enterprise#7398]
When loading a data grid the SohoDataGridSourceRequest object type is checked. This type variable is now not present in the request object causing our data grids to not load.

I initialize the gridOptions:
private loadDataFromServiceEndPoint() {
		// this.dataGrid.disableClientFilter = true; // prevents filtered event from triggering on load.
		console.log('loadDataFromService reached');
		this.dataGrid.disableClientFilter = false;
		this.dataGrid.paging = true;
		this.dataGrid.filterable = true;
		this.dataGrid.pagesizes = [10, 25, 50, 75, 150];
		this.dataGrid.clickToSelect = false;
		this.dataGrid.saveUserSettings = {
			activePage: true,
			columns: true,
			filter: true,
			pagesize: true,
			sortOrder: true
		};
		this.dataGrid.source = (req: SohoDataGridSourceRequest, response: SohoDataGridResponseFunction) => {
			console.log('called get form data about to call get grid data');
			this.getFormData();
			this.gridService.getGridData(**req**, response, this.busyIndicator, this.advancedFilters, !this.areFilterButtonsDisabled);
		};
	}
The request object created is always created without a type now that I have upgraded to the latest version. This is not working for any type initial or filtered.

Before Upgrade: 
<img width="158" alt="image" src="https://user-images.githubusercontent.com/129091848/229561155-c01ae4be-82b7-4a06-92be-8d962088f34c.png">

After Upgrade:
<img width="225" alt="image" src="https://user-images.githubusercontent.com/129091848/229561663-133dd9b2-6542-4389-b00f-894cd05ea5e1.png">
*The filtered variables are also not present after the upgrade*

**Expected behavior**
It is expected for this type variable to be present in the request object as it was before updating to the latest IDS version

**Version**
ids-enterprise: 4.81.1
ids-enterprise-ng: 15.0.5

**Platform**
Infor Automotive Exchange

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.

**Comment by pallisj** [comment]
@tmcconechy @andriivarhanov  I upgraded to the 4.82.0 beta release and this issue is still occurring. I still am not receiving a type variable in my SohoDataGridSourceRequest object. Is there something new I need to set now? Why is req.type no longer present in this object?

This is what the object is looking like as of right now:
<img width="214" alt="image" src="https://user-images.githubusercontent.com/129091848/230497607-6d30488f-d6e1-4ced-8e62-9f049d1d25bc.png">

**Comment by tmcconechy** [comment]
@pallisj I tried this by updating beta on main of https://github.com/infor-design/enterprise-ng
If you clone that repo and `npm i` and run it and go to http://localhost:4200/ids-enterprise-ng-demo/datagrid-fixedheader you can see the type in the console. So seems working.

Maybe check if you updated right?

<img width="1102" alt="Screenshot 2023-04-07 at 9 59 01 AM" src="https://user-images.githubusercontent.com/814283/230621582-3b19b89d-1a2b-4552-8888-592dd71af3f4.png">

@andriivarhanov may reach out on teams. But i see it working on our end.

**Comment by pallisj** [comment]
I sent @andriivarhanov the requested files and double checked that my ids-enterprise version is 4.82.0-beta.0
