### ISSUE TITLE
Modal: No horizontal scrollbar

### ISSUE THREAD

**Issue by radovaniljic** [infor-design/enterprise#7827]
**Describe the bug**
Due to [this rule](https://github.com/infor-design/enterprise/blob/a1d586753e6ed1cff5ead98bdb67a387f87d2cf1/src/components/modal/_modal.scss#L759-L763C4), long horizontal content in modals is cut and no scrollbar appears.

**To Reproduce**
1. Go to https://stackblitz.com/edit/ids-quick-start-1651-3pjhpt
2. Click on "Open Modal"
3. Notice the overflowing content and no scrollbar

**Expected behavior**
A scrollbar should appear

**Version**

- ids-enterprise: `4.85.0`

**Platform**
 - Infor Application/Team Name: Homepages / OS Portal

**Comment by tmcconechy** [comment]
Probably remove that rule and set 
```
.modal-content .modal-body-wrapper {
    overflow: auto;
  }
  ```

If that doesnt bust any examples

**Comment by yohannahbautista** [comment]
Hello, on trying to replicate this in both IDS and NG, it looks to have already been fixed in later versions. I copy-pasted the code on the latest stackblitz and scroll works: https://stackblitz.com/edit/ids-quick-start-1671-pxzgwa?file=src%2Fapp%2Fapp.component.ts

**Comment by radovaniljic** [comment]
@yohannahbautista I can still reproduce it in your stackblitz. Try making the preview wider, as that rule is only applied in landscape mode.

**Comment by tmcconechy** [comment]
@yohannahbautista i think the fix involves removing this rule https://github.com/infor-design/enterprise/blob/a1d586753e6ed1cff5ead98bdb67a387f87d2cf1/src/components/modal/_modal.scss#L759-L763C4 

And reproducing it means applying it at that breakpoint.

Will have to go back in history and see why it was added and make sure we fix that problem why it was added a different way. Or confirm it no longer exists. 👍🏻
