### ISSUE TITLE
PopupMenu: Something changed that caused text wrapping to change

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#8161]
**Describe the bug**

From 4.70 to now something changed in the popupmenu. Any ideas @ericangeles @yohannahbautista @tjamesallen15 
Now the white space is not trimmed. This causes extra spaces in the text node. https://jira.infor.com/browse/LMWEB-18605

**To Reproduce**
1. Go to https://4700-enterprise.demo.design.infor.com/components/popupmenu/example-submenus.html
2. Click on submenu item and inspect
3. Look at properties and then text
4. See that the html is

```
<a href="#" role="menuitem" tabindex="-1" aria-haspopup="true"><span>Submenu 1</span><svg class="arrow icon-dropdown icon" focusable="false" aria-hidden="true" role="presentation"><use href="#icon-dropdown"></use></svg></a>
```
5. Thats all correct but try main and notice the html, this adds / to the text

```
<a href="#" role="menuitem" tabindex="-1" aria-haspopup="true"><span>Submenu 1</span><svg class="arrow icon-dropdown icon" focusable="false" role="presentation" aria-hidden="true">
        <use href="#icon-dropdown"></use>
      </svg></a>
```

**Expected behavior**
Same as 4.70

**Screenshots**
<img width="642" alt="Screenshot 2023-11-08 at 2 10 05 PM" src="https://github.com/infor-design/enterprise/assets/814283/46670fac-0d42-4c8e-9949-34fc5d34f7a0">
<img width="825" alt="Screenshot 2023-11-08 at 2 08 34 PM" src="https://github.com/infor-design/enterprise/assets/814283/3e34e3ce-d7cd-4494-934c-4d619da2b8a9">

**Comment by tmcconechy** [comment]
@ericangeles can you look at this one? I would love to know if you can figure out what changed?

**Comment by yohannahbautista** [comment]
Hello, I think this may have been fixed? Looking at properties in both local and main and I don't see any extra spaces
<img width="278" alt="image" src="https://github.com/infor-design/enterprise/assets/85279127/015cc332-12fd-4f1c-96a8-05f38f27dc79">

**Comment by tmcconechy** [comment]
@yohannahbautista i still see it. Make sure you select the <a> tag like this screen shot

<img width="1617" alt="Screenshot 2023-11-17 at 10 07 30 AM" src="https://github.com/infor-design/enterprise/assets/814283/09fac00f-2f21-4aaf-b1b1-47b0bbe747ca">
