### ISSUE TITLE
New component: 4*4 tile like component request

### ISSUE THREAD

**Issue by infor-mahesh** [infor-design/enterprise#8343]
require a component resembling below
![image](https://github.com/infor-design/enterprise/assets/139130328/246f14e5-712b-4423-a0f4-11e3012ac421)

please look into this

**Comment by tmcconechy** [comment]
@infor-mahesh we already have this component already see:

https://main-enterprise.demo.design.infor.com/components/link/example-index.html
https://main-enterprise.demo.design.infor.com/components/stats/example-index.html

Can you use those? Looks the same. Yours seems to be a bit unbalanced in the design

**Comment by infor-mahesh** [comment]
But we dont have any angular that is enterprise-ng component, please provide link if so

**Comment by tmcconechy** [comment]
I will close this as we have implemented this design to use

**Comment by kuldeepsingh1905** [comment]
HI @tmcconechy ,  we are building our widget using portal widget SDK and we it is still not supporting to use Web component, need ng component version to go for further implementation.

Web component usage on widget SDK has denied by Ravi, he told to ask you/Ben to help us to provide ng component for this, could we please reopen this ticket again.

Thanks Tim for your support. 

Regards,
Kuldeep Singh

**Comment by tmcconechy** [comment]
I think that the new web component SDK will be able to use web components soon in a coming version so you could wait for that. But if not you could just do it like this:

https://github.com/infor-design/enterprise/blob/main/app/views/components/stats/example-index.html#L12

And use markup. I dont see why markup cant be used in an angular app? Doesn't seem like it needs a special component wrapper as its rather simple markup. Just add that to the page? Wont this work?

The web component version is better tho and you should be able to use it as above soon in the SDK.
