### ISSUE TITLE
Editor: Inserted clickable anchor/link does not work on Safari and iOS

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#907]
**Describe the bug**
Editor: Inserted clickable anchor/link does not work on Safari and iOS.
Clicking the inserted link does not open the specified URL.

**To Reproduce**
1. Go to http://4110-beta1-enterprise.demo.design.infor.com/components/editor/example-clickable-links.html in Mac Safari or any iOS browsers
2. Click the "Insert Anchor" button
3. On the Insert Anchor modal, type http://www.google.com in the URL field
4. Check the "Clickable in editor" checkbox
5. Click Insert button
6. Click the inserted anchor/link, Google will not open.
7. Test this on both "New Window" and "Same Window" options, both of them doesn't work

**Expected behavior**
Specified URL should open when the inserted clickable anchor/link was clicked

**Screenshots**
No applicable screenshots.

**Platform**
 - Mac Safari
 - All iOS browsers

**Additional context**
No additional context

**Comment by tmcconechy** [comment]
It might not be possible to make this work in safari IOS, if its not could be an option to hide this from the dialog on the unsupported devices.

**Comment by brianjuan** [comment]
@tmcconechy Noted on the iOS devices, thanks. 
Please also try this on MacOS Safari, this issue also happens there.

**Comment by EdwardCoyle** [comment]
Not sure exactly when and how, but I'm seeing this issue fixed against our latest release:  http://4220-enterprise.demo.design.infor.com/components/editor/example-clickable-links.html

**Comment by tmcconechy** [comment]
Yeah seeing it fixed as well. Oh well, Win! i guess

**Comment by brianjuan** [comment]
Tested this ticket but the issue still persists on the following pages using Mac Safari and all iOS browsers.
http://4220-enterprise.demo.design.infor.com/components/editor/example-clickable-links.html
http://4230-enterprise.demo.design.infor.com/components/editor/example-clickable-links.html
http://master-enterprise.demo.design.infor.com/components/editor/example-clickable-links.html

**Comment by tmcconechy** [comment]
Issue is fixed against local. Lets retest master again.

**Comment by brianjuan** [comment]
I'm not sure why but the issue still persist in Mac Safari, clicking inserted link still does not open unless you do **_command + click_**
Tested in:
http://4240-beta0-enterprise.demo.design.infor.com/components/editor/example-clickable-links.html
http://master-enterprise.demo.design.infor.com/components/editor/example-clickable-links.html

**Comment by EdwardCoyle** [comment]
@brianjuan I'm not seeing that in Mac Safari - clicking the link without `command` seems to work.

My Safari version:
<img width="306" alt="Screen Shot 2019-12-12 at 9 07 56 AM" src="https://user-images.githubusercontent.com/3249601/70718871-0bc4ce80-1cbf-11ea-811f-608a7f96b126.png">

I thought maybe it was a preference in the browser settings, but it seems that it's on by default:  https://apple.stackexchange.com/questions/170731/how-to-open-link-in-a-new-tab-via-shortcut-in-chrome-on-mac

**Comment by tmcconechy** [comment]
Im not seeing this either - lets just ignore this issue. Even if you do have to click with command thats not really an issue worth pursuing anyways.

**Comment by jbrcna** [comment]
Hello, I was testing the `Editor` component and I came across this issue. please see my findings below.
https://master-enterprise.demo.design.infor.com/components/editor/example-clickable-links.html
![Large GIF (1378x468)](https://user-images.githubusercontent.com/56722184/95735705-c21a8b00-0cb7-11eb-9eb0-6f6a38cb7879.gif)
v4.34.0-dev - Safari browser

![image](https://user-images.githubusercontent.com/56722184/95735820-ed9d7580-0cb7-11eb-81d8-984384bf5ee5.png)


Hope this helps 
![image](https://user-images.githubusercontent.com/56722184/95736017-3ead6980-0cb8-11eb-8056-2e30eecefb71.png)

**Comment by tmcconechy** [comment]
Yes this is correct. Some one did ask for this. If its "clickable in the editor"you get the hover state and can click it. But if not its just a readonly like and you get no hover state and cannot click it.

So i think this is working correctly

**Comment by jbrcna** [comment]
Thank you for clarifying @tmcconechy.
